name: remote ssh command
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.USERNAME }}
          password:
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /var/www/Miranda-Laravel
            git pull origin main
            composer install
            artisan migrate
            systemctl restart apache2
